services:

  POSTGRES:
    image: postgres:15-alpine
      #container_name: POSTGRES
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - POSTGRES-DATA:/var/lib/postgresql/data
    networks:
      - MyNetwork

  BACKEND:
    build: ./BackEND
    image: newbackend  
      #container_name: django_backend
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    depends_on:
      - POSTGRES
    networks:
      - MyNetwork
    develop:
      watch:
        - action: sync
          path: ./BackEND
          target: /app
          ignore:
            - __pycache__/
            - "*.sqlite3"
        - action: rebuild
          path: ./BackEND/requirements.txt
        - action: rebuild
          path: ./BackEND/Dockerfile

  FRONTEND:
    build: ./FrontEND
    image: newfrontend
      #container_name: nextjs_frontend
    restart: always
    depends_on:
      - BACKEND
    networks:
      - MyNetwork    
    develop:
      watch:
        - action: sync
          path: ./FrontEND
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: ./FrontEND/package.json
        - action: rebuild
          path: ./FrontEND/Dockerfile

  NGINX:
    image: nginx:alpine
      #container_name: nginx_proxy
    restart: always
    depends_on:
      - FRONTEND
      - BACKEND
    volumes:
      - ./NGINX/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    networks:
      - MyNetwork
    
volumes:
  POSTGRES-DATA:

networks:
  MyNetwork:
    driver: bridge

