"""
Django settings for MyCore project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# در production باید از طریق متغیر محیطی DJANGO_SECRET_KEY ست شود.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-fgc_14rg)31pwx!lo=tc0)jl#hb*l+h$d46z1jq8=t$mptiqi8',
)

# SECURITY WARNING: don't run with debug turned on in production!
# پیش‌فرض False است؛ فقط برای توسعه‌ی محلی با DJANGO_DEBUG=True فعالش کن.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# در production باید دامنه‌ی واقعی از طریق DJANGO_ALLOWED_HOSTS ست شود
# (مثلاً: DJANGO_ALLOWED_HOSTS=example.com,www.example.com)
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'MyApp',
    'sslserver',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MyCore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MyCore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework
# احراز هویت مبتنی بر Session (کوکی)؛ چون nginx فرانت و بک‌اند را روی یک
# دامنه سرو می‌کند، کوکی به‌صورت first-party کار می‌کند و نیازی به توکن نیست.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# CORS
# اگر فرانت‌اند همیشه از پشت همین nginx (همان دامنه/پورت) صدا زده می‌شود،
# اصلاً به CORS نیازی نیست. این تنظیمات فقط برای حالتی است که در توسعه
# مستقیماً از Next.js dev server (مثلاً localhost:3000) به Django (مثلاً
# localhost:8000) درخواست بزنی، بدون عبور از nginx.
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:3000').split(',')
    if origin.strip()
]
CORS_ALLOW_CREDENTIALS = True  # چون از session/cookie استفاده می‌کنیم

# Session / CSRF
# دامنه‌ی واقعی که از پشت nginx سرو می‌شود را جایگزین مقادیر پایین کن
# (یا از طریق متغیر محیطی CSRF_TRUSTED_ORIGINS بده).
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'CSRF_TRUSTED_ORIGINS',
        'http://localhost',
        'https://94.183.150.153:8443',
        'https://94.183.150.153:8080',
        'https://94.183.150.153:8080'
        ).split(',')
    if origin.strip()
]
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False  # جاوااسکریپت فرانت باید بتواند این کوکی را بخواند
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # یک هفته، در صورت نیاز تغییر بده

# در production حتماً این دو را True کن (روی HTTPS)
SESSION_COOKIE_SECURE = os.environ.get('DJANGO_HTTPS', 'False') == 'True'
CSRF_COOKIE_SECURE = os.environ.get('DJANGO_HTTPS', 'False') == 'True'
